chat_models:
  platform: "openai"
  configs:
    api_key: "sk-Z0MdU0NAXCmiwYF_HwWqoF1SU8yOTx1xpnlRZXkABwM6E50pDv9JY8AgLYs"
    proxy_url: "https://apis.linkin.love/v1"
    default_model: "lilchat-13b"
    summary_model: "lilfunc"
    
# 其他配置
settings:
  max_tokens: 1000
  stream: true
  port: 8080